// Generated by CoffeeScript 1.10.0
(function() {
  var Reise, Station, Verpflegung, app, ref;

  require('angular');

  require('angular-ui-router');

  ref = require('../../core'), Reise = ref.Reise, Station = ref.Station, Verpflegung = ref.Verpflegung;

  app = angular.module('reisekostenabrechnung', ['ui.router']);

  app.config(function($stateProvider, $urlRouterProvider) {
    $urlRouterProvider.otherwise('/');
    return $stateProvider.state('overview', {
      url: '/',
      templateUrl: 'overview.html',
      controller: 'reisenController',
      controllerAs: 'reisen'
    }).state('loading', {
      url: 'loading',
      template: '<h2 style="position:absolute;top:50%;width:100%;text-align:center;' + 'font-weight:200;font-size:20px;margin-top: -10px;">Loading...</h2>'
    });
  });

  app.controller('mainController', function($scope) {
    $scope.adding = false;
    return $scope.addTravel = function() {
      return $scope.adding = true;
    };
  });

  app.controller('reisenController', function() {
    this.reisen = [
      {
        title: 'Meine erste Reise'
      }, {
        title: 'Zweite Reise'
      }
    ];
    this.title = 'Willkommen';
  });

  app.controller('menuController', function() {
    this.open = false;
    this.toggleMenu = function() {
      return this.open = !this.open;
    };
    this.elements = [
      {
        title: 'Einstellungen'
      }, {
        title: 'Speicherort'
      }, {
        title: 'Über'
      }
    ];
  });

  app.controller('addController', function($scope) {
    this.step = 0;
    this.steps = [
      {
        title: 'Allgemein',
        template: 'general'
      }, {
        title: 'Reiseroute',
        template: 'route'
      }, {
        title: 'Verpflegung',
        template: 'flat'
      }, {
        title: 'Belege',
        template: 'bills'
      }
    ];
    this.currentTitle = function() {
      return this.steps[this.step].title;
    };
    this.currentTemplate = function() {
      return 'add-steps/' + this.steps[this.step].template + '.html';
    };
    this.goTo = function(index) {
      return this.step = index;
    };
    this.isStep = function(index) {
      return this.step === index;
    };
    this.next = function() {
      if (this.isLast()) {
        $scope.adding = false;
        return;
      }
      return this.goTo(++this.step);
    };
    this.prev = function() {
      if (this.isFirst()) {
        $scope.adding = false;
        return;
      }
      return this.goTo(--this.step);
    };
    this.isLast = function() {
      return this.step === this.steps.length - 1;
    };
    this.isFirst = function() {
      return this.step === 0;
    };
    this.travel = new Reise('');
    this.setTitle = function(title) {
      return this.travel.setTitle(title);
    };
  });

  app.directive('}menu', function() {
    return {
      templateUrl: 'menu.html',
      controller: 'menuController',
      controllerAs: 'menu'
    };
  });

  app.directive('add', function() {
    return {
      templateUrl: 'add.html',
      controller: 'addController',
      controllerAs: 'adder'
    };
  });

}).call(this);

//# sourceMappingURL=app.js.map
